env: "local"
db:
 dsn: "postgresql://madina:2626@localhost:5432/url_shortener?sslmode=disable"
 maxOpenConns: 25
 maxIdleConns: 25
 maxIdleTime: "15m"
http_server:
 address: "0.0.0.0:8085"
 timeout: "4s"
 idle_timeout: "30s"
